#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Use the version below while working on cookiecutter itself
# cd ./my_awesome_sixie_project/frontend && npx lint-staged
cd ./frontend && npx lint-staged
