image: python:3.10

definitions:
  steps:
    - step: &install-package
        name: Backend Tests
        caches:
          - pip
        script:
          - pip install pytest
          - pytest tests.py

pipelines:
  default:
    - parallel:
      - step: *install-package
