image: python:3.10

definitions:
  services:
    docker:
      memory: 3072

    postgres:
      image: postgres:latest
      environment:
        POSTGRES_HOST: postgres
        POSTGRES_DB: my_awesome_sixie_project
        POSTGRES_USER: my_awesome_sixie_project
        POSTGRES_PASSWORD: TESTPASSWORD

    redis:
      image: redis:stable


  steps:
    - step: &backend-tests
        name: Backend Tests
        caches:
          - pip
        script:
          - export DATABASE_URL=postgres://my_awesome_sixie_project:TESTPASSWORD@postgres:5432/my_awesome_sixie_project

          - export CELERY_BROKER_URL=redis://127.0.0.1:6379/0

          - make backend-test

        services:

          - redis

          - postgres

    - step: &check-lint-and-formatting
        name: Check lint and formatting
        caches:
          - pip
        script:
          - make check-lint-and-formatting


    - step: &check-lint-and-test-frontend
        name: Frontend Lint & Typecheck & Test
        image: node:16-bullseye
        caches:
          - node
        script:
          - make check-lint-and-test-frontend


pipelines:
  default:
    - parallel:
      - step: *check-lint-and-formatting

      - step: *check-lint-and-test-frontend

      - step: *backend-tests
