image: python:3.10

definitions:
  steps:
    - step: &install-package
        name: Backend Tests
        caches:
          - pip
        script:
          - pip install pytest

    - step: &run-test
        script:
          - pytest tests.py

pipelines:
  default:
    - step: *install-package
    - step: *run-test