version: '3.7'
volumes:
  local_postgres_data_my_awesome_sixie_project: {}
  local_postgres_data_my_awesome_sixie_project_backups: {}

services:
  db:
    image: 'postgres:16-bullseye'
    volumes:
      - 'local_postgres_data_my_awesome_sixie_project:/var/lib/postgresql/data'
      - 'local_postgres_data_my_awesome_sixie_project_backups:/backups'
    env_file:
      - backend/local/environment
    ports:
      - '5432:5432'

  django:
    image: 'my_awesome_sixie_project_local_django:dev'
    command: 'python manage.py runserver 0.0.0.0:8000'
    # command: 'gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker'
    volumes:
      - './backend:/app/src:z'
    env_file:
      - backend/local/environment
    depends_on:
      - migrate
      - mailhog
      
      - celerybeat
      - celeryworker
      - flower
      
  migrate:
    image: 'my_awesome_sixie_project_local_django:dev'
    command: python manage.py migrate
    volumes:
      - './backend:/app/src:z'
    env_file:
      - backend/local/environment
    depends_on:
      - db
  
  celeryworker:
    image: 'my_awesome_sixie_project_local_django:dev'
    command: '/app/bin/celery -A my_awesome_sixie_project worker -E -l info'
    volumes:
      - './backend:/app/src:z'
    env_file:
      - backend/local/environment
    depends_on:
      - db
      - redis
  celerybeat:
    image: 'my_awesome_sixie_project_local_django:dev'
    command: '/app/bin/celery -A my_awesome_sixie_project beat'
    volumes:
      - './backend:/app/src:z'
    env_file:
      - backend/local/environment
    depends_on:
      - db
      - redis
  flower:
    image: 'my_awesome_sixie_project_local_django:dev'
    command: '/app/bin/celery -A my_awesome_sixie_project flower'
    volumes:
      - './backend:/app/src:z'
    env_file:
      - backend/local/environment
    depends_on:
      - db
      - redis
  
  
  frontend:
    image: 'my_awesome_sixie_project_local_frontend:dev'
    user: node
    working_dir: /app
    environment:
      - BROWSER=none
    command: npm run dev
    volumes:
      - '/app/node_modules'
      - './frontend:/app'
    stdin_open: true
  
  mailhog:
    image: 'mailhog/mailhog:v1.0.0'
  
  redis:
    image: 'redis:latest'
  
