apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-sandbox-cert
spec:
  secretName: cluster-sandbox-cert-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - "k8s.sandbox.sixfeetup.com"
  - "api.sandbox.sixfeetup.com"
