apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DJANGO_DEBUG: "False"
  USE_DOCKER: "yes"
  DJANGO_ADMIN_URL: "admin/"
  DJANGO_SETTINGS_MODULE: "config.settings.local"
  DJANGO_SECRET_KEY: "CHANGEME"
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,django,sixfeetup.com"
  DJANGO_CSRF_TRUSTED_ORIGINS: "http://localhost,https://sixfeetup.com"
  DJANGO_SECURE_SSL_REDIRECT: "False"
  POSTGRES_USER: "test_project"
  POSTGRES_PASSWORD: "CHANGEME"
  PGDATA: "/var/lib/postgresql/data/pgdata"
  DATABASE_URL: "psql://test_project:CHANGEME@postgres:5432/test_project"
  REDIS_URL: "redis://redis:6379/1"

  # S3 storage access
  AWS_S3_ACCESS_KEY_ID: CHANGEME_S3_IAM_USER
  DJANGO_AWS_S3_REGION_NAME: us-east-1
  DJANGO_AWS_STORAGE_BUCKET_NAME: "CHANGEME_S3_BUCKET_NAME"

  # sentry monitoring
  SENTRY_DSN: ""
